### PR TITLE
Added the new way to run tests

### PR DESCRIPTION
**Pull request by skovsgaard**
I wasn't sure how to go about changing the other places where `lfetool` is mentioned, but I wanted to make the first one up to date with how ltest is being run through rebar3.

Please let me know if anything else needs changing or I should add this somewhere else entirely.

### CODE REVIEW

**Comment by yurrriq** [comment]
@skovsgaard, I've opened a PR on your branch. Please review and feel free to edit as you see fit.

**Comment by skovsgaard** [comment]
It looked fine to me. I like the idea of using profiles. What about the rest of the README. Does it make sense to replace all instances of `lfetool test` with `rebar3 eunit` and if no, do we have any alternatives?

**Comment by skovsgaard** [comment]
And also @yurrriq, your changes are on my branch now.

**Comment by yurrriq** [comment]
:+1: maybe @oubiwann will want to add a paragraph describing the state and planning of lfetool/ltool.

**Comment by oubiwann** [comment]
Thanks!

**Pull request merged**
