### PR TITLE
Compile ltest using rebar3 LFE plugin

### PR DESCRIPTION
**Pull request by John-Goff**
When attempting to use ltest through mix, mix would get confused that the `$REBAR_DEPS_DIR` didn't have the stuff that it expected it to have and would fail. This was ultimately due to ltest using `lfec` directly instead of using the rebar3 plugin. The README states that the plugin is required, so I don't foresee this being a problem, but please try this change out and let me know if there are any issues.

Supersedes #75

### CODE REVIEW

**Comment by oubiwann** [comment]
Generally, these are nice changes.

However, there is some history around the use of the testing mechanism in the rebar config itself ... iirc, it was part of a years-long effort to get rid of all the issues around cyclic dependencies that would come up for different people using different deps (or missing some, or having conflicting versions, etc.). 

I _think_ we had to remove the ltest dep from rebar3_lfe itself to fix everything everywhere.

I'll take a look at the history and get back to you ...

**Comment by oubiwann** [comment]
Yeah, that was it:
* https://github.com/lfex/ltest/commit/07c488a601acbf24049c28c5783bbeee1ac98451

**Comment by oubiwann** [comment]
Let's figure out how to address the issue you ran into without re-introducing the chance for cyclic deps occurring ...

**Comment by John-Goff** [comment]
Oh I see, I didn't realize the rebar3 plugin also depended on ltest. Let me have a think on this and come back with something. Open to suggestions though!

**Comment by John-Goff** [comment]
Alright, circular dependency solved by removing ltest as a dependency of rebar3_lfe. See https://github.com/lfe/rebar3/pull/88 for that change.

**Review by oubiwann — APPROVED** [review]
Okay, let's give this a go and see how it works 😄

**Comment by oubiwann** [comment]
Hrm. CI/CD failed on the older versions of Erlang, now that it's pulling in rebar3_ltest. This was due to a bug/missing feature in rebar3 itself around  Erlang 26's new way of starting up shells.

I had to comment out Erlang 19 and 20 from rebar3_lfe -- you'll need to do the same here, in your branch for the GH Actions CI/CD yaml file.

Push up that change, and I'll kick off another run ...

**Comment by oubiwann** [comment]
NICE!

**Pull request merged**
